### PR TITLE
Added a PDF version of the Tuning Playbook

### PR DESCRIPTION
**Pull request by Anirudh257**
Hi, Thanks for making such a comprehensive document. I created a PDF version of it. Hope this helps!

### CODE REVIEW

**Comment by osbm** [comment]
We can make a github action that automatically generates the pdf file using pandoc after every commit. Then we can release that file in a pre-release or just put it in a new branch named build. So that the git repository wouldn't have to deal with the changes in a binary file.

**Comment by AjinkyaIndulkar** [comment]
might be better to just publish the playbook on GitHub pages.

**Comment by Anirudh257** [comment]
Yes, @AjinkyaIndulkar that makes better sense. It can be updated in real-time with more commits.

**Comment by ferreirafabio** [comment]
Would be great to include the figures in the pdf :)

**Pull request closed without merging**
